GET http://localhost:3000/format
Accept: text/csv

###
GET http://localhost:3000/format-dash
Accept: text/csv
###
GET http://localhost:3000/format-dash
Accept: text/yaml
### XML
GET http://localhost:3000/format-dash
Accept: text/xml
###
GET http://localhost:3000/format-dash-col
Accept: text/xml
###
GET http://localhost:3000/format
Accept: text/xml
###
GET http://localhost:3000/format-col
Accept: text/xml
### YAML
GET http://localhost:3000/format-dash
Accept: text/yml
###
GET http://localhost:3000/format-dash-col
Accept: text/yml
###
GET http://localhost:3000/format
Accept: text/yml
###
GET http://localhost:3000/format-col
Accept: text/yml
###
GET http://localhost:3000/users
Accept: text/xml
###
GET http://localhost:3000/users/1
Accept: text/xml
###
GET http://localhost:3000/users/1/comments
Accept: text/xml
###
GET http://localhost:3000/v1/products
Accept: text/xml
###
GET http://localhost:3000/v2/products
Accept: text/xml
###
GET http://localhost:3000/v4/products
Accept: text/xml
###
GET http://localhost:3000/products?_apiVersion=4
Accept: text/xml
###
GET http://localhost:3000/products
Accept: text/xml
Accept-Version: v1

###
GET http://localhost:3000/v1/products
Accept: text/xml

###
GET http://localhost:3000/clothes2
Accept-Language: fr;q=0.8, *;q=0.9